"""
Types for API v2.

The API is versioned by path, so its types are versioned too: import them from
`uptimer.models.v2`, the way resources are reached through `client.v2`. Nothing
here is re-exported from `uptimer.models` — a v2 name is only ever a v2 import.

Version-independent deserialization exceptions live in `uptimer.models.errors`,
because they say nothing about which API version raised them.
"""

from .acknowledgement import (
    IncidentAcknowledgement,
    SubjectIncident,
)
from .deserialize import (
    from_api,
    from_api_acknowledgement,
    from_api_delivery_record,
    from_api_destination,
    from_api_incident,
    from_api_location,
    from_api_maintenance,
    from_api_observation,
    from_api_signal,
    from_api_subject,
    from_api_subject_delivery,
    from_api_subject_incident,
    from_api_subject_rule,
    from_api_transformation,
    from_api_transformation_preview,
    from_api_website_monitor,
    from_api_workspace,
)
from .incident import (
    STATUS_NO_DATA,
    STATUS_OK,
    STATUS_PENDING,
    STATUS_PROBLEM,
    STATUS_RECOVERING,
    Incident,
    IncidentLocations,
)
from .location import Location
from .maintenance import MaintenanceWindow
from .monitor import (
    AGREEMENT_ALL,
    AGREEMENT_ANY,
    AGREEMENT_MAJORITY,
    BaseWebsiteMonitor,
    CreateWebsiteMonitorRequest,
    DeleteWebsiteMonitorResponse,
    UpdateWebsiteMonitorRequest,
    WebsiteMonitor,
    WebsiteMonitorRequest,
    WebsiteMonitorResponse,
    WebsiteMonitorResponseBody,
)
from .notifications import (
    ALERT_KIND_NO_DATA,
    ALERT_KIND_PROBLEM,
    ALERT_KIND_RECOVERY,
    ALERT_KINDS,
    DELIVERY_STATUS_DELIVERED,
    DELIVERY_STATUS_FAILED,
    DESTINATION_TYPE_SLACK,
    DESTINATION_TYPE_WEBHOOK,
    FALLBACK_SILENCE,
    FALLBACK_WORKSPACE_DEFAULT,
    CreateDestinationRequest,
    CreateTransformationRequest,
    DeleteDestinationResponse,
    DeleteTransformationResponse,
    DeliveryRecord,
    DeliverySelection,
    Destination,
    PreviewResult,
    SubjectAlertDelivery,
    TestDeliveryResponse,
    Transformation,
    TransformationPreview,
    TransformationSample,
    UpdateDestinationRequest,
    UpdateTransformationRequest,
    samples_from_api,
)
from .observation import (
    REJECT_ACCEPTED,
    REJECT_CLOCK_SKEW,
    REJECT_LATE,
    REJECT_OUT_OF_ORDER,
    REJECT_OUT_OF_RETENTION,
    CreateObservationRequest,
    Observation,
)
from .observation import (
    STATUS_OK as OBSERVATION_STATUS_OK,
)
from .observation import (
    STATUS_PROBLEM as OBSERVATION_STATUS_PROBLEM,
)
from .rule import (
    INPUT_MODE_LATEST_VALUE,
    INPUT_MODE_STATUS,
    NEED_ALL,
    NEED_ANY,
    NEED_AT_LEAST,
    NEED_MAJORITY,
    RULE_STATE_DOWN,
    CreateRuleRequest,
    DeleteRuleResponse,
    RuleDecision,
    RuleDocument,
    RuleInput,
    RuleWait,
    SubjectRule,
    UpdateRuleRequest,
    rule_document_from_api,
    rule_document_to_api,
)
from .signal import (
    SIGNAL_KIND_EVENT,
    SIGNAL_KIND_HEARTBEAT,
    SIGNAL_KIND_HTTP,
    CreateSignalRequest,
    DeleteSignalResponse,
    Signal,
    UpdateSignalRequest,
)
from .subject import (
    SUBJECT_KIND_CUSTOM,
    SUBJECT_KIND_WEBSITE,
    CreateSubjectRequest,
    Subject,
)
from .workspace import Workspace

__all__ = [
    "AGREEMENT_ALL",
    "AGREEMENT_ANY",
    "AGREEMENT_MAJORITY",
    "ALERT_KINDS",
    "ALERT_KIND_NO_DATA",
    "ALERT_KIND_PROBLEM",
    "ALERT_KIND_RECOVERY",
    "DELIVERY_STATUS_DELIVERED",
    "DELIVERY_STATUS_FAILED",
    "DESTINATION_TYPE_SLACK",
    "DESTINATION_TYPE_WEBHOOK",
    "FALLBACK_SILENCE",
    "FALLBACK_WORKSPACE_DEFAULT",
    "INPUT_MODE_LATEST_VALUE",
    "INPUT_MODE_STATUS",
    "NEED_ALL",
    "NEED_ANY",
    "NEED_AT_LEAST",
    "NEED_MAJORITY",
    "OBSERVATION_STATUS_OK",
    "OBSERVATION_STATUS_PROBLEM",
    "REJECT_ACCEPTED",
    "REJECT_CLOCK_SKEW",
    "REJECT_LATE",
    "REJECT_OUT_OF_ORDER",
    "REJECT_OUT_OF_RETENTION",
    "RULE_STATE_DOWN",
    "SIGNAL_KIND_EVENT",
    "SIGNAL_KIND_HEARTBEAT",
    "SIGNAL_KIND_HTTP",
    "STATUS_NO_DATA",
    "STATUS_OK",
    "STATUS_PENDING",
    "STATUS_PROBLEM",
    "STATUS_RECOVERING",
    "SUBJECT_KIND_CUSTOM",
    "SUBJECT_KIND_WEBSITE",
    "BaseWebsiteMonitor",
    "CreateDestinationRequest",
    "CreateObservationRequest",
    "CreateRuleRequest",
    "CreateSignalRequest",
    "CreateSubjectRequest",
    "CreateTransformationRequest",
    "CreateWebsiteMonitorRequest",
    "DeleteDestinationResponse",
    "DeleteRuleResponse",
    "DeleteSignalResponse",
    "DeleteTransformationResponse",
    "DeleteWebsiteMonitorResponse",
    "DeliveryRecord",
    "DeliverySelection",
    "Destination",
    "Incident",
    "IncidentAcknowledgement",
    "IncidentLocations",
    "Location",
    "MaintenanceWindow",
    "Observation",
    "PreviewResult",
    "RuleDecision",
    "RuleDocument",
    "RuleInput",
    "RuleWait",
    "Signal",
    "Subject",
    "SubjectAlertDelivery",
    "SubjectIncident",
    "SubjectRule",
    "TestDeliveryResponse",
    "Transformation",
    "TransformationPreview",
    "TransformationSample",
    "UpdateDestinationRequest",
    "UpdateRuleRequest",
    "UpdateSignalRequest",
    "UpdateTransformationRequest",
    "UpdateWebsiteMonitorRequest",
    "WebsiteMonitor",
    "WebsiteMonitorRequest",
    "WebsiteMonitorResponse",
    "WebsiteMonitorResponseBody",
    "Workspace",
    "from_api",
    "from_api_acknowledgement",
    "from_api_delivery_record",
    "from_api_destination",
    "from_api_incident",
    "from_api_location",
    "from_api_maintenance",
    "from_api_observation",
    "from_api_signal",
    "from_api_subject",
    "from_api_subject_delivery",
    "from_api_subject_incident",
    "from_api_subject_rule",
    "from_api_transformation",
    "from_api_transformation_preview",
    "from_api_website_monitor",
    "from_api_workspace",
    "rule_document_from_api",
    "rule_document_to_api",
    "samples_from_api",
]
